### ISSUE TITLE
Page: Start / Login

### ISSUE THREAD

**Issue by ncbecker** [ncbecker/podium#17]
# Related to user story

#1 #2 

# Tasks

- [ ] Implement components
- [ ] Check and adjust responsiveness
- [ ] Add animation to logo
- [ ] Add animation to theme toggler
