### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by ncbecker** [ncbecker/podium#24]
# Description

Create Login / Start Page and necessary components

# Related to user story

#1 #2

# Notes and resources

https://styled-components.com/docs/advanced#theming
https://www.joshwcomeau.com/react/boop/

# Tasks

- [x] Theme toggler icon
- [x] Log in with Spotify button
- [x] Skip log in and info icon
- [x] Info bubble (show onclick and onhover)
- [x] Import logo svg
- [ ] Add animation to logo
- [ ] Add animation to theme toggler
- [x] Check and adjust responsiveness
- [x] Create page
- [x] Create stories for page and components
