### ISSUE TITLE
Voting Interface Page

### ISSUE THREAD

**Issue by ncbecker** [ncbecker/podium#25]
# Description

Create Voting Interface Page and necessary components

# Related to user story

#3 #4 #6 #7 #8

# Notes and resources

https://lottiefiles.com/8821-like-button?lang=de
https://www.joshwcomeau.com/react/boop/

# Tasks

- [x] Episode card item (manage overflow of longer titles with three dots)
- [x] Burger menu icon
- [x] Filter icon with hover animation
- [x] Input for search with suggested results
- [x] Like button and counter
- [x] Set up LottieFile animation for likes
- [x] Check and adjust responsiveness
- [x] Create page
- [x] Create stories for page and components
