### ISSUE TITLE
Menu Page (logged in)

### ISSUE THREAD

**Issue by ncbecker** [ncbecker/podium#26]
# Description

Create Menu Page (logged in) and necessary components

# Related to user story

#7

# Notes and resources

# Tasks

- [x] Return icon
- [x] Log out icon
- [x] User welcome title (manage overflow of longer user names)
- [x] Favorites title
- [x] Episode card item (overlapping component)
- [x] Check and adjust responsiveness
- [x] Create page
- [x] Create stories for page and components
