### ISSUE TITLE
Menu Page (NOT logged in)

### ISSUE THREAD

**Issue by ncbecker** [ncbecker/podium#27]
# Description

Create Menu Page (NOT logged in) and necessary components

# Related to user story

#8

# Notes and resources

# Tasks

- [x] Return icon
- [x] Logo (overlapping component)
- [x] Log in button (overlapping component)
- [x] Check and adjust responsiveness
- [x] Create page
- [x] Create stories for page and components
