### ISSUE TITLE
Search Suggestion Page 

### ISSUE THREAD

**Issue by ncbecker** [ncbecker/podium#28]
# Description

Create Menu Page (NOT logged in) and necessary components

# Related to user story

#8

# Notes and resources

# Tasks

- [ ] Return icon
- [ ] Logo (overlapping component)
- [ ] Log in button (overlapping component)
- [ ] Check and adjust responsiveness
- [ ] Create page
- [ ] Create stories for page and components
