### ISSUE TITLE
Episode Details Page

### ISSUE THREAD

**Issue by ncbecker** [ncbecker/podium#29]
# Description

Create Episode Details Page and necessary components

# Related to user story

#9

# Notes and resources

# Tasks

## Stage 1 Feature: Details and add to Spotify

- [x] Return icon (overlapping component)
- [x] Episode picture, title, show, show notes and statistics
- [x] Add icon
- [x] Like icon and animation (overlapping component)
- [x] Check and adjust responsiveness
- [x] Create page
- [x] Create stories for page and components

## Stage 2 Feature: Comment section

- [ ] Comment icon and counter
- [ ] Comment box and comments with correct styling
- [ ] Delete icon

**Comment by ncbecker** [comment]
Stage 2 Features will be implemented at later stage
