### ISSUE TITLE
Filter Overlay Page

### ISSUE THREAD

**Issue by ncbecker** [ncbecker/podium#30]
# Description

Create Filter Overlay Page and necessary components

# Related to user story

#4

# Notes and resources

# Tasks

- [x] Exit icon
- [x] Titles
- [x] Selections / check boxes with intelligent dependencies and validation
- [x] Check and adjust responsiveness
- [x] Create page
- [x] Create stories for page and components
