### ISSUE TITLE
Add animations

### ISSUE THREAD

**Issue by ncbecker** [ncbecker/podium#41]
# Notes and resources

https://www.joshwcomeau.com/react/boop/

# Tasks

- [ ] Add animation to logo on login page
- [ ] Add ease-in and -out to info bubble
- [ ] Add animation to theme toggler and other icons
